/**
 * Generates vocab/hotwords.generated.txt from the wiki (and optionally the source repo it documents).
 *
 *   npm run vocab -- [--wiki <dir> ...] [--repo <dir>] [--limit 300] [--out <file>]
 *
 * Terms already in vocab/hotwords.txt are skipped: the manual list always wins.
 */
import { readFile, readdir, writeFile } from 'node:fs/promises';
import { basename, extname, join, resolve } from 'node:path';
import { parseArgs } from 'node:util';
import { loadConfig } from '../src/config.ts';
import { WikiStore } from '../src/wiki/store.ts';
import { GENERATED_VOCAB_FILE, MANUAL_VOCAB_FILE, extractTerms, parseVocabFile, rankTerms } from '../src/vocab.ts';

const CODE_EXTENSIONS = new Set(['.ts', '.tsx', '.js', '.mjs', '.go', '.py', '.rs', '.java', '.kt', '.cs', '.rb', '.swift']);
const SKIP_DIRS = new Set(['node_modules', 'vendor', 'dist', 'build', 'target', 'out', 'coverage', '__pycache__']);
const DEFINITION_RE =
  /\b(?:class|interface|type|enum|struct|trait|func|function|def|fn)\s+(?:\([^)]*\)\s*)?([A-Za-z_][A-Za-z0-9_]{3,})/g;
const MAX_REPO_FILES = 20_000;

async function* walk(dir: string, count = { n: 0 }): AsyncGenerator<string> {
  let entries;
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch {
    return;
  }
  for (const entry of entries) {
    if (entry.name.startsWith('.') || SKIP_DIRS.has(entry.name)) continue;
    const path = join(dir, entry.name);
    if (entry.isDirectory()) yield* walk(path, count);
    else if (entry.isFile() && CODE_EXTENSIONS.has(extname(entry.name)) && count.n++ < MAX_REPO_FILES) yield path;
  }
}

/** Type/function names defined in the repo, weighted by how often they are defined; plus source file names. */
async function repoTerms(repoDir: string): Promise<string[]> {
  const terms: string[] = [];
  for await (const file of walk(repoDir)) {
    const name = basename(file);
    if (/[A-Z_-]/.test(name.slice(0, -extname(name).length))) terms.push(name);
    const source = await readFile(file, 'utf8').catch(() => '');
    for (const m of source.matchAll(DEFINITION_RE)) {
      const id = m[1]!;
      if (/[a-z][A-Z]|_/.test(id) || /^[A-Z][a-z]+[A-Z]/.test(id)) terms.push(id);
    }
  }
  return terms;
}

async function main(): Promise<void> {
  const cfg = loadConfig();
  const { values } = parseArgs({
    options: {
      wiki: { type: 'string', multiple: true },
      repo: { type: 'string' },
      limit: { type: 'string', default: '300' },
      out: { type: 'string', default: join(cfg.VOCAB_DIR, GENERATED_VOCAB_FILE) },
    },
  });
  const limit = Number.parseInt(values.limit, 10);
  if (!Number.isFinite(limit) || limit <= 0) throw new Error(`invalid --limit ${values.limit}`);

  const sources = values.wiki
    ? values.wiki.map((path, index) => ({ id: `wiki-${index + 1}`, name: basename(path), path: resolve(path) }))
    : cfg.WIKI_SOURCES;
  const store = new WikiStore(sources);
  await store.load();
  const terms: string[] = [];
  const metaPages = new Set([...store.indexes(), ...store.logs()].map((page) => `${page.sourceId}:${page.path}`));
  for (const page of store.pages()) {
    // Page titles are what people say out loud most, so they count double.
    if (!metaPages.has(`${page.sourceId}:${page.path}`)) terms.push(page.title, page.title);
    terms.push(...extractTerms(page.content));
  }
  if (values.repo) terms.push(...(await repoTerms(resolve(values.repo))));

  const manual = await readFile(join(cfg.VOCAB_DIR, MANUAL_VOCAB_FILE), 'utf8')
    .then(parseVocabFile)
    .catch(() => []);
  const ranked = rankTerms(terms, limit, manual);
  const header = [
    '# Generated by `npm run vocab` — do not edit; put manual terms in hotwords.txt instead.',
    `# Sources: ${sources.map(({ id, path }) => `${id}=${path}`).join(', ')}${values.repo ? ` + ${values.repo}` : ''} (${store.size} pages), ${new Date().toISOString()}`,
  ];
  await writeFile(values.out, `${[...header, ...ranked].join('\n')}\n`);
  console.log(`Wrote ${ranked.length} terms to ${values.out}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
