export const LANGUAGES = [
  { code: 'en', label: 'English', short: 'EN' },
  { code: 'nl', label: 'Nederlands', short: 'NL' },
] as const;

export type Language = (typeof LANGUAGES)[number]['code'];

const STORAGE_KEY = 'llm-wiki-avatar.language';

export function isLanguage(value: unknown): value is Language {
  return LANGUAGES.some((l) => l.code === value);
}

export function loadLanguage(fallback: Language = 'en'): Language {
  if (typeof window === 'undefined') return fallback;
  const stored = window.localStorage.getItem(STORAGE_KEY);
  if (isLanguage(stored)) return stored;
  return navigator.language.toLowerCase().startsWith('nl') ? 'nl' : fallback;
}

export function saveLanguage(language: Language): void {
  window.localStorage.setItem(STORAGE_KEY, language);
}

/** UI strings; the agent handles the spoken side. */
export const STRINGS = {
  en: {
    title: 'Talk to the wiki',
    subtitle: 'Ask questions about the code base out loud. Code and details show up on screen.',
    start: 'Start conversation',
    connecting: 'Connecting…',
    waiting: 'Waiting for the agent…',
    listening: 'Listening',
    thinking: 'Thinking',
    speaking: 'Speaking',
    hearing: 'Hearing you…',
    transcribing: 'Processing your speech…',
    preparing: 'Preparing an answer…',
    end: 'End',
    typePlaceholder: 'Or type a question…',
    send: 'Send',
    stop: 'Stop',
    stopSpeaking: 'Stop speaking',
    transcript: 'Transcript',
    onScreen: 'On screen',
    sources: 'Sources',
    noSources: 'Pages used for the answer appear here.',
    close: 'Close',
    language: 'Language',
    pushToTalk: 'Push to talk',
    holdToTalk: 'Hold to talk (or hold Space)',
    talking: 'Release to send',
    noSpeechModel: 'Choose a speech model in the speech settings to talk',
    loadingSpeechModel: 'Loading speech model…',
    speechModelFailed: 'The speech model could not be loaded. Check the speech settings.',
    micUnavailable: 'The microphone is not available.',
    settings: 'Settings',
    modelConnection: 'Model connection',
    configuredProvider: 'Configured provider',
    configuredAuth: 'Authentication',
    apiKeyAuth: 'API key / local placeholder',
    entraSetup: 'Set up Microsoft Entra ID / Enterprise gateway',
    entraIntro: 'Use the gateway’s OpenAI v1 API. Set the model to a deployment name, not a generic model name. Obtain the required gateway/model RBAC permissions and an authorized account or identity from your organization. Replace the example endpoint and resource scope with the values supplied by your gateway administrator. No LLM_API_KEY is needed: Azure Identity caches and refreshes access tokens automatically.',
    entraCli: 'For native local development, install Azure CLI and sign in to the tenant with gateway access before starting the agent. The standard agent Docker image has neither Azure CLI nor your host login; use service-principal mode in Compose instead.',
    entraServicePrincipal: 'For Docker or deployments outside Azure, use an authorized service principal. Keep its secret only in the agent server environment. Set the application (client) ID, not the object ID; never use the secret as LLM_API_KEY. Auto mode chooses service-principal authentication if any AZURE_* credential field is set (all three are then required), otherwise Azure CLI.',
    entraManagedIdentity: 'On an Azure host with managed identity, set ENTRA_AUTH_MODE=managed-identity. For a user-assigned identity also set AZURE_CLIENT_ID to its client ID and assign gateway roles. Without it, the system-assigned identity is used. No client secret is required; this mode does not use AKS federated workload identity.',
    entraProduction: 'A production example is https://api.example.com/openai/v1 with ENTRA_SCOPE=api://api.example.com/.default. Replace both with your gateway’s values; endpoint and scope must belong to the same environment. Leave reasoning effort unset; use LLM_TEMPERATURE=omit when the deployment does not support temperature. A 401 can indicate a wrong tenant/scope; a 403 usually means missing permissions.',
    entraCa: 'For a private corporate CA, export NODE_EXTRA_CA_CERTS to a PEM certificate path before starting Node. In Docker, mount the certificate read-only and set the path inside the container. Do not disable TLS verification. Full examples are in the repository README.',
    configuredModel: 'Configured model',
    legacyProvider: 'OpenAI-compatible endpoint (legacy configuration)',
    modelNotSet: 'Not set',
    modelConfigNote: 'Server configuration, not a connection health check. Changes apply to new conversations after restarting the services.',
    apiSetup: 'Set up a third-party API',
    apiSetupIntro: 'Obtain an API key from OpenAI or an OpenAI-compatible provider. Choose a chat-completion model with streaming and tool calling, then set these values in the server environment. Replace the model and key placeholders; use your provider’s API base URL.',
    apiSetupKey: 'Keep the real key only in the server environment or an uncommitted environment file. Never put it in browser storage or NEXT_PUBLIC_* variables. Native Anthropic and Gemini APIs need a compatible gateway and are not supported directly.',
    apiDockerOverride: 'For Docker, remove any old LLM_BASE_URL_DOCKER override or change it to the same API URL: it takes precedence over LLM_BASE_URL. No Ollama containers or images are needed.',
    modelPrivacy: 'Hosted providers receive your questions, wiki excerpts, tool results and conversation context, including restored history. API usage may incur charges. Audio recognition and reply voices stay in this browser. Restrict public access to prevent unauthorized API spending.',
    ollamaSetup: 'Set up Ollama',
    ollamaNative: 'Install Ollama from ollama.com and start it on the host (ollama serve if needed). Pull a tool-capable model, then use these server settings. Native Ollama is faster on macOS because Docker cannot use Metal.',
    ollamaDocker: 'To run Ollama in Docker instead, use the Ollama settings above plus this endpoint override. The optional ollama profile starts Ollama and pulls LLM_MODEL. Set an Ollama model name before enabling it, not a hosted API model name.',
    ollamaHost: 'With a Docker agent and native Ollama, use LLM_BASE_URL_DOCKER=http://host.docker.internal:11434/v1. With a native agent use localhost; with both in Compose use the ollama service hostname. Docker’s localhost is not your host machine.',
    ollamaProd: 'For published production images, add -f docker-compose.prod.yml to the Docker commands and omit --build. Ollama images are only pulled and started when the ollama profile is enabled.',
    modelApply: 'Apply changes or switch back to Ollama',
    modelEnv: 'Native services read the repository .env.local before .env. Compose reads .env by default; add --env-file .env.local to every Compose command if that is your configuration file.',
    modelRestart: 'After editing configuration, restart the native agent and frontend, or recreate both containers with the command below. A Docker restart alone does not reload environment values. End any existing conversation and start a new one.',
    modelFallback: 'Fallback is manual, never automatic: set LLM_PROVIDER=ollama and LLM_AUTH=api-key, restore an Ollama model, endpoint and LLM_API_KEY=ollama, then recreate the services. Start native Ollama or enable its Docker profile. An API error will not silently send your conversation to another provider.',
    modelTroubleshooting: 'Check agent logs: authentication failures usually mean the key, Entra login or token scope is invalid; model-not-found means the model/deployment ID or API base URL is wrong. For connection errors check the hostname and service. Increase LLM_TIMEOUT_S for slow models; use LLM_TEMPERATURE=omit or leave LLM_REASONING_EFFORT unset when unsupported. Models must support streaming and tool calling.',
    speechSettings: 'Speech settings',
    settingsTitle: 'Speech recognition',
    settingsIntro:
      'Speech recognition and voices run right here in the browser. Download them once; the browser keeps them for next time.',
    backToApp: 'Back to the conversation',
    thisBrowser: 'This browser',
    webgpuYes: 'WebGPU available: models run on the graphics card.',
    webgpuNoF16: 'WebGPU available, without 16-bit float support: the largest model is not available.',
    webgpuNo: 'No WebGPU: models run on the processor, which is slower. Chrome and Edge support WebGPU.',
    storageUsed: 'Storage used',
    recommended: 'Recommended',
    inUse: 'In use',
    use: 'Use',
    download: 'Download',
    resumeDownload: 'Continue download',
    downloading: 'Downloading…',
    cancel: 'Cancel',
    remove: 'Remove',
    confirmRemove: 'Remove this model from the browser?',
    downloaded: 'Downloaded',
    partlyDownloaded: 'Partly downloaded',
    notDownloaded: 'Not downloaded',
    needsWebgpuF16: 'Needs WebGPU with 16-bit float support',
    downloadFailed: 'Download failed',
    tryIt: 'Try it',
    tryItHint: 'Hold the button (or Space) and say something.',
    tryItNoModel: 'Download a model and select it first.',
    nothingRecognized: 'Nothing recognized.',
    transcribedIn: 'Transcribed in',
    voices: 'Voices',
    voicesIntro: 'Replies are spoken by a voice that runs in this browser. Download the voices for the languages you use.',
    female: 'Female',
    male: 'Male',
    wordTimings: 'Word timings (premium avatar)',
    confirmRemoveVoice: 'Remove this voice from the browser?',
    tryVoice: 'Try a voice',
    tryVoiceNone: 'Download a voice first.',
    speak: 'Speak',
    preparingSpeech: 'Preparing speech…',
    voiceFailed: 'The voice failed:',
    firstAudioAfter: 'First audio after',
    speechLength: 'speech',
    synthesizedIn: 'synthesized in',
    instantTranscript: 'Show dialog without delay',
    instantTranscriptNote: 'Show replies as soon as they arrive, instead of along with the voice.',
    voiceMissing: 'The voice for this language is not downloaded, so replies are text only.',
    voiceFailedShort: 'The voice could not be played; replies are text only.',
    empty: 'Say hello, or ask something like "How are Stripe webhooks retried?"',
    history: 'Conversations',
    noHistory: 'Past conversations appear here.',
    today: 'Today',
    yesterday: 'Yesterday',
    previous7Days: 'Previous 7 days',
    untitled: 'Conversation',
    continueConversation: 'Continue conversation',
    continuing: 'Continuing an earlier conversation',
    deleteConversation: 'Delete',
    confirmDelete: 'Delete this conversation?',
    clearHistory: 'Clear all',
    confirmClear: 'Delete all saved conversations?',
    showHistory: 'Show conversations',
    hideHistory: 'Hide conversations',
    historyNote: 'Saved in this browser only.',
    presentation: 'Voice and avatar',
    presentationOff: 'Off (text replies only)',
    voiceFemale: 'Voice only, female',
    voiceMale: 'Voice only, male',
    avatarFemale: 'Voice and avatar, female',
    avatarFemalePremium: 'Voice and avatar, female (premium)',
    avatarFemale2: 'Voice and avatar, female 2',
    avatarMale: 'Voice and avatar, male',
    aiAvatar: 'AI avatar',
    loadingAvatar: 'Loading avatar…',
    avatarCredit: 'Ember by VTubeMe',
    switchingVoice: 'Switching voice…',
    answering: 'Answering',
    textOnly: 'Replies as text only',
    voiceOnly: 'Voice only',
  },
  nl: {
    title: 'Praat met de wiki',
    subtitle: 'Stel hardop vragen over de code. Code en details verschijnen op het scherm.',
    start: 'Gesprek starten',
    connecting: 'Verbinden…',
    waiting: 'Wachten op de agent…',
    listening: 'Luistert',
    thinking: 'Denkt na',
    speaking: 'Spreekt',
    hearing: 'Hoort je…',
    transcribing: 'Spraak verwerken…',
    preparing: 'Antwoord voorbereiden…',
    end: 'Stoppen',
    typePlaceholder: 'Of typ een vraag…',
    send: 'Versturen',
    stop: 'Stop',
    stopSpeaking: 'Stoppen met praten',
    transcript: 'Transcript',
    onScreen: 'Op het scherm',
    sources: 'Bronnen',
    noSources: 'Gebruikte pagina’s verschijnen hier.',
    close: 'Sluiten',
    language: 'Taal',
    pushToTalk: 'Drukken om te praten',
    holdToTalk: 'Ingedrukt houden om te praten (of houd spatie ingedrukt)',
    talking: 'Loslaten om te versturen',
    noSpeechModel: 'Kies een spraakmodel in de spraakinstellingen om te praten',
    loadingSpeechModel: 'Spraakmodel laden…',
    speechModelFailed: 'Het spraakmodel kon niet worden geladen. Kijk in de spraakinstellingen.',
    micUnavailable: 'De microfoon is niet beschikbaar.',
    settings: 'Instellingen',
    modelConnection: 'Modelverbinding',
    configuredProvider: 'Ingestelde provider',
    configuredAuth: 'Authenticatie',
    apiKeyAuth: 'API-sleutel / lokale placeholder',
    entraSetup: 'Microsoft Entra ID / Enterprise-gateway instellen',
    entraIntro: 'Gebruik de OpenAI-v1-API van de gateway. Stel het model in op een deploymentnaam, niet een algemene modelnaam. Regel de vereiste gateway- en modelrechten en een geautoriseerd account of een identity bij je organisatie. Vervang het voorbeeldendpoint en de resourcescope door de waarden van je gatewaybeheerder. LLM_API_KEY is niet nodig: Azure Identity bewaart en vernieuwt toegangstokens automatisch.',
    entraCli: 'Installeer voor native lokale ontwikkeling Azure CLI en meld je aan bij de tenant met gatewaytoegang voordat je de agent start. Het standaard Docker-image bevat geen Azure CLI of je hostaanmelding; gebruik in Compose de service-principalmodus.',
    entraServicePrincipal: 'Gebruik voor Docker of deployments buiten Azure een geautoriseerde service principal. Bewaar het geheim alleen in de serveromgeving van de agent. Gebruik het applicatie-ID (client-ID), niet het object-ID; gebruik het geheim nooit als LLM_API_KEY. Auto kiest service-principalauthenticatie als een AZURE_*-credentialveld is ingesteld (alle drie zijn dan vereist), anders Azure CLI.',
    entraManagedIdentity: 'Stel op een Azure-host met managed identity ENTRA_AUTH_MODE=managed-identity in. Zet voor een user-assigned identity ook AZURE_CLIENT_ID op het client-ID en ken gatewayrollen toe. Zonder dit ID wordt de system-assigned identity gebruikt. Een client secret is niet nodig; deze modus gebruikt geen gefedereerde AKS-workloadidentiteit.',
    entraProduction: 'Een productievoorbeeld is https://api.example.com/openai/v1 met ENTRA_SCOPE=api://api.example.com/.default. Vervang beide door de waarden van je gateway; endpoint en scope moeten bij dezelfde omgeving horen. Laat reasoning effort leeg; gebruik LLM_TEMPERATURE=omit als de deployment temperature niet ondersteunt. Een 401 kan op een verkeerde tenant of scope wijzen; een 403 betekent meestal ontbrekende rechten.',
    entraCa: 'Exporteer voor een interne CA NODE_EXTRA_CA_CERTS met het pad naar een PEM-certificaat voordat Node start. Mount in Docker het certificaat alleen-lezen en gebruik het pad in de container. Schakel TLS-controle niet uit. Volledige voorbeelden staan in de README van de repository.',
    configuredModel: 'Ingesteld model',
    legacyProvider: 'OpenAI-compatibel endpoint (bestaande configuratie)',
    modelNotSet: 'Niet ingesteld',
    modelConfigNote: 'Serverconfiguratie, geen controle van de verbinding. Wijzigingen gelden voor nieuwe gesprekken na het herstarten van de diensten.',
    apiSetup: 'Een externe API instellen',
    apiSetupIntro: 'Maak een API-sleutel bij OpenAI of een OpenAI-compatibele provider. Kies een chat-completionmodel met streaming en toolaanroepen en zet deze waarden in de serveromgeving. Vervang het model en de sleutel; gebruik de API-basis-URL van je provider.',
    apiSetupKey: 'Bewaar de echte sleutel alleen in de serveromgeving of een omgevingsbestand dat niet wordt gecommit. Gebruik nooit browseropslag of NEXT_PUBLIC_*-variabelen. Native Anthropic- en Gemini-API’s vereisen een compatibele gateway en worden niet rechtstreeks ondersteund.',
    apiDockerOverride: 'Verwijder voor Docker een oude LLM_BASE_URL_DOCKER of wijzig deze naar dezelfde API-URL: deze heeft voorrang op LLM_BASE_URL. Ollama-containers en -images zijn niet nodig.',
    modelPrivacy: 'Externe providers ontvangen je vragen, wiki-fragmenten, toolresultaten en gesprekscontext, inclusief herstelde geschiedenis. API-gebruik kan geld kosten. Spraakherkenning en stemmen blijven in deze browser. Beperk openbare toegang om ongewenste API-kosten te voorkomen.',
    ollamaSetup: 'Ollama instellen',
    ollamaNative: 'Installeer Ollama via ollama.com en start het op de host (zo nodig met ollama serve). Download een model met toolondersteuning en gebruik deze serverinstellingen. Native Ollama is sneller op macOS omdat Docker geen Metal kan gebruiken.',
    ollamaDocker: 'Gebruik voor Ollama in Docker de instellingen hierboven plus deze endpoint-override. Het optionele ollama-profiel start Ollama en downloadt LLM_MODEL. Stel eerst een Ollama-modelnaam in, niet de naam van een extern API-model.',
    ollamaHost: 'Gebruik met een Docker-agent en native Ollama LLM_BASE_URL_DOCKER=http://host.docker.internal:11434/v1. Gebruik voor een native agent localhost; gebruik voor beide in Compose de servicenaam ollama. Localhost in Docker is niet je hostmachine.',
    ollamaProd: 'Voeg voor gepubliceerde productie-images -f docker-compose.prod.yml toe aan de Docker-opdrachten en laat --build weg. Ollama-images worden alleen gedownload en gestart als het ollama-profiel is ingeschakeld.',
    modelApply: 'Wijzigingen toepassen of terug naar Ollama',
    modelEnv: 'Native diensten lezen .env.local in de repository vóór .env. Compose leest standaard .env; voeg --env-file .env.local toe aan elke Compose-opdracht als je dat bestand gebruikt.',
    modelRestart: 'Herstart na wijzigingen de native agent en frontend, of maak beide containers opnieuw aan met de opdracht hieronder. Alleen een Docker-herstart laadt geen nieuwe omgevingswaarden. Beëindig een bestaand gesprek en start een nieuw gesprek.',
    modelFallback: 'Terugvallen gebeurt handmatig, nooit automatisch: stel LLM_PROVIDER=ollama en LLM_AUTH=api-key in, herstel een Ollama-model, endpoint en LLM_API_KEY=ollama en maak de diensten opnieuw aan. Start native Ollama of schakel het Docker-profiel in. Bij een API-fout gaat je gesprek niet stilzwijgend naar een andere provider.',
    modelTroubleshooting: 'Bekijk de agentlogs: bij authenticatiefouten klopt meestal de sleutel, Entra-aanmelding of tokenscope niet; bij model-not-found klopt het model/deployment-ID of de API-basis-URL niet. Controleer bij verbindingsfouten de hostnaam en dienst. Verhoog LLM_TIMEOUT_S bij trage modellen; gebruik LLM_TEMPERATURE=omit of laat LLM_REASONING_EFFORT leeg als deze niet worden ondersteund. Modellen moeten streaming en toolaanroepen ondersteunen.',
    speechSettings: 'Spraakinstellingen',
    settingsTitle: 'Spraakherkenning',
    settingsIntro:
      'Spraakherkenning en stemmen draaien hier in de browser. Download ze één keer; de browser bewaart ze voor de volgende keer.',
    backToApp: 'Terug naar het gesprek',
    thisBrowser: 'Deze browser',
    webgpuYes: 'WebGPU beschikbaar: modellen draaien op de grafische kaart.',
    webgpuNoF16: 'WebGPU beschikbaar, zonder 16-bit float-ondersteuning: het grootste model is niet beschikbaar.',
    webgpuNo: 'Geen WebGPU: modellen draaien op de processor, wat trager is. Chrome en Edge ondersteunen WebGPU.',
    storageUsed: 'Gebruikte opslag',
    recommended: 'Aanbevolen',
    inUse: 'In gebruik',
    use: 'Gebruiken',
    download: 'Downloaden',
    resumeDownload: 'Download hervatten',
    downloading: 'Downloaden…',
    cancel: 'Annuleren',
    remove: 'Verwijderen',
    confirmRemove: 'Dit model uit de browser verwijderen?',
    downloaded: 'Gedownload',
    partlyDownloaded: 'Deels gedownload',
    notDownloaded: 'Niet gedownload',
    needsWebgpuF16: 'Vereist WebGPU met 16-bit float-ondersteuning',
    downloadFailed: 'Downloaden mislukt',
    tryIt: 'Uitproberen',
    tryItHint: 'Houd de knop (of spatie) ingedrukt en zeg iets.',
    tryItNoModel: 'Download eerst een model en selecteer het.',
    nothingRecognized: 'Niets herkend.',
    transcribedIn: 'Omgezet in',
    voices: 'Stemmen',
    voicesIntro:
      'Antwoorden worden uitgesproken door een stem die in deze browser draait. Download de stemmen voor de talen die je gebruikt.',
    female: 'Vrouw',
    male: 'Man',
    wordTimings: 'Woordtiming (premium-avatar)',
    confirmRemoveVoice: 'Deze stem uit de browser verwijderen?',
    tryVoice: 'Een stem uitproberen',
    tryVoiceNone: 'Download eerst een stem.',
    speak: 'Uitspreken',
    preparingSpeech: 'Spraak voorbereiden…',
    voiceFailed: 'De stem werkt niet:',
    firstAudioAfter: 'Eerste geluid na',
    speechLength: 'spraak',
    synthesizedIn: 'gemaakt in',
    instantTranscript: 'Dialoog zonder vertraging tonen',
    instantTranscriptNote: 'Toon antwoorden zodra ze binnenkomen, in plaats van samen met de stem.',
    voiceMissing: 'De stem voor deze taal is niet gedownload; antwoorden zijn alleen tekst.',
    voiceFailedShort: 'De stem kon niet worden afgespeeld; antwoorden zijn alleen tekst.',
    empty: 'Zeg hallo, of vraag bijvoorbeeld "Hoe worden Stripe-webhooks opnieuw geprobeerd?"',
    history: 'Gesprekken',
    noHistory: 'Eerdere gesprekken verschijnen hier.',
    today: 'Vandaag',
    yesterday: 'Gisteren',
    previous7Days: 'Afgelopen 7 dagen',
    untitled: 'Gesprek',
    continueConversation: 'Gesprek voortzetten',
    continuing: 'Een eerder gesprek wordt voortgezet',
    deleteConversation: 'Verwijderen',
    confirmDelete: 'Dit gesprek verwijderen?',
    clearHistory: 'Alles wissen',
    confirmClear: 'Alle bewaarde gesprekken verwijderen?',
    showHistory: 'Gesprekken tonen',
    hideHistory: 'Gesprekken verbergen',
    historyNote: 'Alleen in deze browser bewaard.',
    presentation: 'Stem en avatar',
    presentationOff: 'Uit (alleen tekstantwoorden)',
    voiceFemale: 'Alleen stem, vrouw',
    voiceMale: 'Alleen stem, man',
    avatarFemale: 'Stem en avatar, vrouw',
    avatarFemalePremium: 'Stem en avatar, vrouw (premium)',
    avatarFemale2: 'Stem en avatar, vrouw 2',
    avatarMale: 'Stem en avatar, man',
    aiAvatar: 'AI-avatar',
    loadingAvatar: 'Avatar laden…',
    avatarCredit: 'Ember door VTubeMe',
    switchingVoice: 'Stem wisselen…',
    answering: 'Antwoordt',
    textOnly: 'Antwoorden alleen als tekst',
    voiceOnly: 'Alleen stem',
  },
} satisfies Record<Language, Record<string, string>>;

export type Strings = (typeof STRINGS)['en'];
