export const LANGUAGES = [
  { code: 'en', label: 'English', short: 'EN' },
  { code: 'nl', label: 'Nederlands', short: 'NL' },
] as const;

export type Language = (typeof LANGUAGES)[number]['code'];

const STORAGE_KEY = 'llm-wiki-avatar.language';

export function isLanguage(value: unknown): value is Language {
  return LANGUAGES.some((l) => l.code === value);
}

export function loadLanguage(fallback: Language = 'en'): Language {
  if (typeof window === 'undefined') return fallback;
  const stored = window.localStorage.getItem(STORAGE_KEY);
  if (isLanguage(stored)) return stored;
  return navigator.language.toLowerCase().startsWith('nl') ? 'nl' : fallback;
}

export function saveLanguage(language: Language): void {
  window.localStorage.setItem(STORAGE_KEY, language);
}

/** UI strings; the agent handles the spoken side. */
export const STRINGS = {
  en: {
    title: 'Talk to the wiki',
    subtitle: 'Ask questions about the code base out loud. Code and details show up on screen.',
    start: 'Start conversation',
    connecting: 'Connecting…',
    waiting: 'Waiting for the agent…',
    listening: 'Listening',
    thinking: 'Thinking',
    speaking: 'Speaking',
    hearing: 'Hearing you…',
    transcribing: 'Processing your speech…',
    preparing: 'Preparing an answer…',
    end: 'End',
    typePlaceholder: 'Or type a question…',
    send: 'Send',
    stop: 'Stop',
    stopSpeaking: 'Stop speaking',
    transcript: 'Transcript',
    onScreen: 'On screen',
    sources: 'Sources',
    noSources: 'Pages used for the answer appear here.',
    close: 'Close',
    language: 'Language',
    pushToTalk: 'Push to talk',
    holdToTalk: 'Hold to talk (or hold Space)',
    talking: 'Release to send',
    noSpeechModel: 'Choose a speech model in the speech settings to talk',
    loadingSpeechModel: 'Loading speech model…',
    speechModelFailed: 'The speech model could not be loaded. Check the speech settings.',
    micUnavailable: 'The microphone is not available.',
    speechSettings: 'Speech settings',
    settingsTitle: 'Speech recognition',
    settingsIntro:
      'Speech recognition and voices run right here in the browser. Download them once; the browser keeps them for next time.',
    backToApp: 'Back to the conversation',
    thisBrowser: 'This browser',
    webgpuYes: 'WebGPU available: models run on the graphics card.',
    webgpuNoF16: 'WebGPU available, without 16-bit float support: the largest model is not available.',
    webgpuNo: 'No WebGPU: models run on the processor, which is slower. Chrome and Edge support WebGPU.',
    storageUsed: 'Storage used',
    recommended: 'Recommended',
    inUse: 'In use',
    use: 'Use',
    download: 'Download',
    resumeDownload: 'Continue download',
    downloading: 'Downloading…',
    cancel: 'Cancel',
    remove: 'Remove',
    confirmRemove: 'Remove this model from the browser?',
    downloaded: 'Downloaded',
    partlyDownloaded: 'Partly downloaded',
    notDownloaded: 'Not downloaded',
    needsWebgpuF16: 'Needs WebGPU with 16-bit float support',
    downloadFailed: 'Download failed',
    tryIt: 'Try it',
    tryItHint: 'Hold the button (or Space) and say something.',
    tryItNoModel: 'Download a model and select it first.',
    nothingRecognized: 'Nothing recognized.',
    transcribedIn: 'Transcribed in',
    voices: 'Voices',
    voicesIntro: 'Replies are spoken by a voice that runs in this browser. Download the voices for the languages you use.',
    female: 'Female',
    male: 'Male',
    wordTimings: 'Word timings (premium avatar)',
    confirmRemoveVoice: 'Remove this voice from the browser?',
    tryVoice: 'Try a voice',
    tryVoiceNone: 'Download a voice first.',
    speak: 'Speak',
    preparingSpeech: 'Preparing speech…',
    voiceFailed: 'The voice failed:',
    firstAudioAfter: 'First audio after',
    speechLength: 'speech',
    synthesizedIn: 'synthesized in',
    empty: 'Say hello, or ask something like "How are Stripe webhooks retried?"',
    history: 'Conversations',
    noHistory: 'Past conversations appear here.',
    today: 'Today',
    yesterday: 'Yesterday',
    previous7Days: 'Previous 7 days',
    untitled: 'Conversation',
    continueConversation: 'Continue conversation',
    continuing: 'Continuing an earlier conversation',
    deleteConversation: 'Delete',
    confirmDelete: 'Delete this conversation?',
    clearHistory: 'Clear all',
    confirmClear: 'Delete all saved conversations?',
    showHistory: 'Show conversations',
    hideHistory: 'Hide conversations',
    historyNote: 'Saved in this browser only.',
    presentation: 'Voice and avatar',
    presentationOff: 'Off (text replies only)',
    voiceFemale: 'Voice only, female',
    voiceMale: 'Voice only, male',
    avatarFemale: 'Voice and avatar, female',
    avatarFemalePremium: 'Voice and avatar, female (premium)',
    avatarMale: 'Voice and avatar, male',
    aiAvatar: 'AI avatar',
    switchingVoice: 'Switching voice…',
    answering: 'Answering',
    textOnly: 'Replies as text only',
    voiceOnly: 'Voice only',
  },
  nl: {
    title: 'Praat met de wiki',
    subtitle: 'Stel hardop vragen over de code. Code en details verschijnen op het scherm.',
    start: 'Gesprek starten',
    connecting: 'Verbinden…',
    waiting: 'Wachten op de agent…',
    listening: 'Luistert',
    thinking: 'Denkt na',
    speaking: 'Spreekt',
    hearing: 'Hoort je…',
    transcribing: 'Spraak verwerken…',
    preparing: 'Antwoord voorbereiden…',
    end: 'Stoppen',
    typePlaceholder: 'Of typ een vraag…',
    send: 'Versturen',
    stop: 'Stop',
    stopSpeaking: 'Stoppen met praten',
    transcript: 'Transcript',
    onScreen: 'Op het scherm',
    sources: 'Bronnen',
    noSources: 'Gebruikte pagina’s verschijnen hier.',
    close: 'Sluiten',
    language: 'Taal',
    pushToTalk: 'Drukken om te praten',
    holdToTalk: 'Ingedrukt houden om te praten (of houd spatie ingedrukt)',
    talking: 'Loslaten om te versturen',
    noSpeechModel: 'Kies een spraakmodel in de spraakinstellingen om te praten',
    loadingSpeechModel: 'Spraakmodel laden…',
    speechModelFailed: 'Het spraakmodel kon niet worden geladen. Kijk in de spraakinstellingen.',
    micUnavailable: 'De microfoon is niet beschikbaar.',
    speechSettings: 'Spraakinstellingen',
    settingsTitle: 'Spraakherkenning',
    settingsIntro:
      'Spraakherkenning en stemmen draaien hier in de browser. Download ze één keer; de browser bewaart ze voor de volgende keer.',
    backToApp: 'Terug naar het gesprek',
    thisBrowser: 'Deze browser',
    webgpuYes: 'WebGPU beschikbaar: modellen draaien op de grafische kaart.',
    webgpuNoF16: 'WebGPU beschikbaar, zonder 16-bit float-ondersteuning: het grootste model is niet beschikbaar.',
    webgpuNo: 'Geen WebGPU: modellen draaien op de processor, wat trager is. Chrome en Edge ondersteunen WebGPU.',
    storageUsed: 'Gebruikte opslag',
    recommended: 'Aanbevolen',
    inUse: 'In gebruik',
    use: 'Gebruiken',
    download: 'Downloaden',
    resumeDownload: 'Download hervatten',
    downloading: 'Downloaden…',
    cancel: 'Annuleren',
    remove: 'Verwijderen',
    confirmRemove: 'Dit model uit de browser verwijderen?',
    downloaded: 'Gedownload',
    partlyDownloaded: 'Deels gedownload',
    notDownloaded: 'Niet gedownload',
    needsWebgpuF16: 'Vereist WebGPU met 16-bit float-ondersteuning',
    downloadFailed: 'Downloaden mislukt',
    tryIt: 'Uitproberen',
    tryItHint: 'Houd de knop (of spatie) ingedrukt en zeg iets.',
    tryItNoModel: 'Download eerst een model en selecteer het.',
    nothingRecognized: 'Niets herkend.',
    transcribedIn: 'Omgezet in',
    voices: 'Stemmen',
    voicesIntro:
      'Antwoorden worden uitgesproken door een stem die in deze browser draait. Download de stemmen voor de talen die je gebruikt.',
    female: 'Vrouw',
    male: 'Man',
    wordTimings: 'Woordtiming (premium-avatar)',
    confirmRemoveVoice: 'Deze stem uit de browser verwijderen?',
    tryVoice: 'Een stem uitproberen',
    tryVoiceNone: 'Download eerst een stem.',
    speak: 'Uitspreken',
    preparingSpeech: 'Spraak voorbereiden…',
    voiceFailed: 'De stem werkt niet:',
    firstAudioAfter: 'Eerste geluid na',
    speechLength: 'spraak',
    synthesizedIn: 'gemaakt in',
    empty: 'Zeg hallo, of vraag bijvoorbeeld "Hoe worden Stripe-webhooks opnieuw geprobeerd?"',
    history: 'Gesprekken',
    noHistory: 'Eerdere gesprekken verschijnen hier.',
    today: 'Vandaag',
    yesterday: 'Gisteren',
    previous7Days: 'Afgelopen 7 dagen',
    untitled: 'Gesprek',
    continueConversation: 'Gesprek voortzetten',
    continuing: 'Een eerder gesprek wordt voortgezet',
    deleteConversation: 'Verwijderen',
    confirmDelete: 'Dit gesprek verwijderen?',
    clearHistory: 'Alles wissen',
    confirmClear: 'Alle bewaarde gesprekken verwijderen?',
    showHistory: 'Gesprekken tonen',
    hideHistory: 'Gesprekken verbergen',
    historyNote: 'Alleen in deze browser bewaard.',
    presentation: 'Stem en avatar',
    presentationOff: 'Uit (alleen tekstantwoorden)',
    voiceFemale: 'Alleen stem, vrouw',
    voiceMale: 'Alleen stem, man',
    avatarFemale: 'Stem en avatar, vrouw',
    avatarFemalePremium: 'Stem en avatar, vrouw (premium)',
    avatarMale: 'Stem en avatar, man',
    aiAvatar: 'AI-avatar',
    switchingVoice: 'Stem wisselen…',
    answering: 'Antwoordt',
    textOnly: 'Antwoorden alleen als tekst',
    voiceOnly: 'Alleen stem',
  },
} satisfies Record<Language, Record<string, string>>;

export type Strings = (typeof STRINGS)['en'];
