export const LANGUAGES = [
  { code: 'en', label: 'English', short: 'EN' },
  { code: 'nl', label: 'Nederlands', short: 'NL' },
] as const;

export type Language = (typeof LANGUAGES)[number]['code'];

const STORAGE_KEY = 'llm-wiki-avatar.language';

export function isLanguage(value: unknown): value is Language {
  return LANGUAGES.some((l) => l.code === value);
}

export function loadLanguage(fallback: Language = 'en'): Language {
  if (typeof window === 'undefined') return fallback;
  const stored = window.localStorage.getItem(STORAGE_KEY);
  if (isLanguage(stored)) return stored;
  return navigator.language.toLowerCase().startsWith('nl') ? 'nl' : fallback;
}

export function saveLanguage(language: Language): void {
  window.localStorage.setItem(STORAGE_KEY, language);
}

/** UI strings; the agent handles the spoken side. */
export const STRINGS = {
  en: {
    title: 'Talk to the wiki',
    subtitle: 'Ask questions about the code base out loud. Code and details show up on screen.',
    start: 'Start conversation',
    connecting: 'Connecting…',
    waiting: 'Waiting for the agent…',
    listening: 'Listening',
    thinking: 'Thinking',
    speaking: 'Speaking',
    hearing: 'Hearing you…',
    transcribing: 'Processing your speech…',
    preparing: 'Preparing an answer…',
    end: 'End',
    typePlaceholder: 'Or type a question…',
    send: 'Send',
    stop: 'Stop',
    stopSpeaking: 'Stop speaking',
    transcript: 'Transcript',
    onScreen: 'On screen',
    sources: 'Sources',
    noSources: 'Pages used for the answer appear here.',
    close: 'Close',
    language: 'Language',
    pushToTalk: 'Push to talk',
    holdToTalk: 'Hold to talk (or hold Space)',
    talking: 'Release to send',
    noSpeechModel: 'Choose a speech model in the speech settings to talk',
    loadingSpeechModel: 'Loading speech model…',
    speechModelFailed: 'The speech model could not be loaded. Check the speech settings.',
    micUnavailable: 'The microphone is not available.',
    settings: 'Settings',
    modelConnection: 'Model connection',
    configuredProvider: 'Configured provider',
    configuredAuth: 'Authentication',
    apiKeyAuth: 'API key / local placeholder',
    entraSetup: 'Set up Microsoft Entra ID / Enterprise gateway',
    entraIntro: 'Use the gateway’s OpenAI v1 API. Set the model to a deployment name, not a generic model name. Obtain the required gateway/model RBAC permissions and an authorized account or identity from your organization. Replace the example endpoint and resource scope with the values supplied by your gateway administrator. No LLM_API_KEY is needed: Azure Identity caches and refreshes access tokens automatically.',
    entraCli: 'For native local development, install Azure CLI and sign in to the tenant with gateway access before starting the agent. The standard agent Docker image has neither Azure CLI nor your host login; use service-principal mode in Compose instead.',
    entraServicePrincipal: 'For Docker or deployments outside Azure, use an authorized service principal. Keep its secret only in the agent server environment. Set the application (client) ID, not the object ID; never use the secret as LLM_API_KEY. Auto mode chooses service-principal authentication if any AZURE_* credential field is set (all three are then required), otherwise Azure CLI.',
    entraManagedIdentity: 'On an Azure host with managed identity, set ENTRA_AUTH_MODE=managed-identity. For a user-assigned identity also set AZURE_CLIENT_ID to its client ID and assign gateway roles. Without it, the system-assigned identity is used. No client secret is required; this mode does not use AKS federated workload identity.',
    entraProduction: 'A production example is https://api.example.com/openai/v1 with ENTRA_SCOPE=api://api.example.com/.default. Replace both with your gateway’s values; endpoint and scope must belong to the same environment. Leave reasoning effort unset; use LLM_TEMPERATURE=omit when the deployment does not support temperature. A 401 can indicate a wrong tenant/scope; a 403 usually means missing permissions.',
    entraCa: 'For a private corporate CA, export NODE_EXTRA_CA_CERTS to a PEM certificate path before starting Node. In Docker, mount the certificate read-only and set the path inside the container. Do not disable TLS verification. Full examples are in the repository README.',
    configuredModel: 'Configured model',
    legacyProvider: 'OpenAI-compatible endpoint (legacy configuration)',
    modelNotSet: 'Not set',
    modelConfigNote: 'Server configuration, not a connection health check. Changes apply to new conversations after restarting the services.',
    apiSetup: 'Set up a third-party API',
    apiSetupIntro: 'Obtain an API key from OpenAI or an OpenAI-compatible provider. Choose a chat-completion model with streaming and tool calling, then set these values in the server environment. Replace the model and key placeholders; use your provider’s API base URL.',
    apiSetupKey: 'Keep the real key only in the server environment or an uncommitted environment file. Never put it in browser storage or NEXT_PUBLIC_* variables. Native Anthropic and Gemini APIs need a compatible gateway and are not supported directly.',
    apiDockerOverride: 'For Docker, remove any old LLM_BASE_URL_DOCKER override or change it to the same API URL: it takes precedence over LLM_BASE_URL. No Ollama containers or images are needed.',
    modelPrivacy: 'Hosted providers receive your questions, wiki excerpts, tool results and conversation context, including restored history. API usage may incur charges. Audio recognition and reply voices stay in this browser. Restrict public access to prevent unauthorized API spending.',
    ollamaSetup: 'Set up Ollama',
    ollamaNative: 'Install Ollama from ollama.com and start it on the host (ollama serve if needed). Pull a tool-capable model, then use these server settings. Native Ollama is faster on macOS because Docker cannot use Metal.',
    ollamaDocker: 'To run Ollama in Docker instead, use the Ollama settings above plus this endpoint override. The optional ollama profile starts Ollama and pulls LLM_MODEL. Set an Ollama model name before enabling it, not a hosted API model name.',
    ollamaHost: 'With a Docker agent and native Ollama, use LLM_BASE_URL_DOCKER=http://host.docker.internal:11434/v1. With a native agent use localhost; with both in Compose use the ollama service hostname. Docker’s localhost is not your host machine.',
    ollamaProd: 'For published production images, add -f docker-compose.prod.yml to the Docker commands and omit --build. Ollama images are only pulled and started when the ollama profile is enabled.',
    modelApply: 'Apply changes or switch back to Ollama',
    modelEnv: 'Native services read the repository .env.local before .env. Compose reads .env by default; add --env-file .env.local to every Compose command if that is your configuration file.',
    modelRestart: 'After editing configuration, restart the native agent and frontend, or recreate both containers with the command below. A Docker restart alone does not reload environment values. End any existing conversation and start a new one.',
    modelFallback: 'Fallback is manual, never automatic: set LLM_PROVIDER=ollama and LLM_AUTH=api-key, restore an Ollama model, endpoint and LLM_API_KEY=ollama, then recreate the services. Start native Ollama or enable its Docker profile. An API error will not silently send your conversation to another provider.',
    modelTroubleshooting: 'Check agent logs: authentication failures usually mean the key, Entra login or token scope is invalid; model-not-found means the model/deployment ID or API base URL is wrong. For connection errors check the hostname and service. Increase LLM_TIMEOUT_S for slow models; use LLM_TEMPERATURE=omit or leave LLM_REASONING_EFFORT unset when unsupported. Models must support streaming and tool calling.',
    speechSettings: 'Speech settings',
    settingsTitle: 'Speech recognition',
    settingsIntro:
      'Speech recognition and voices run right here in the browser. Download them once; the browser keeps them for next time.',
    backToApp: 'Back to the conversation',
    thisBrowser: 'This browser',
    webgpuYes: 'WebGPU available: models run on the graphics card.',
    webgpuNoF16: 'WebGPU available, without 16-bit float support: the largest model is not available.',
    webgpuNo: 'No WebGPU: models run on the processor, which is slower. Chrome and Edge support WebGPU.',
    storageUsed: 'Storage used',
    recommended: 'Recommended',
    inUse: 'In use',
    use: 'Use',
    download: 'Download',
    resumeDownload: 'Continue download',
    downloading: 'Downloading…',
    cancel: 'Cancel',
    remove: 'Remove',
    confirmRemove: 'Remove this model from the browser?',
    downloaded: 'Downloaded',
    partlyDownloaded: 'Partly downloaded',
    notDownloaded: 'Not downloaded',
    needsWebgpuF16: 'Needs WebGPU with 16-bit float support',
    downloadFailed: 'Download failed',
    tryIt: 'Try it',
    tryItHint: 'Hold the button (or Space) and say something.',
    tryItNoModel: 'Download a model and select it first.',
    nothingRecognized: 'Nothing recognized.',
    transcribedIn: 'Transcribed in',
    voices: 'Voices',
    voicesIntro: 'Replies are spoken by a voice that runs in this browser. Download the voices for the languages you use.',
    female: 'Female',
    male: 'Male',
    wordTimings: 'Word timings (avatar lip-sync)',
    confirmRemoveVoice: 'Remove this voice from the browser?',
    tryVoice: 'Try a voice',
    tryVoiceNone: 'Download a voice first.',
    speak: 'Speak',
    preparingSpeech: 'Preparing speech…',
    voiceFailed: 'The voice failed:',
    firstAudioAfter: 'First audio after',
    speechLength: 'speech',
    synthesizedIn: 'synthesized in',
    instantTranscript: 'Show dialog without delay',
    instantTranscriptNote: 'Show replies as soon as they arrive, instead of along with the voice.',
    voiceMissing: 'The voice for this language is not downloaded, so replies are text only.',
    voiceFailedShort: 'The voice could not be played; replies are text only.',
    empty: 'Say hello, or ask something like "How are Stripe webhooks retried?"',
    history: 'Conversations',
    noHistory: 'Past conversations appear here.',
    today: 'Today',
    yesterday: 'Yesterday',
    previous7Days: 'Previous 7 days',
    untitled: 'Conversation',
    continueConversation: 'Continue conversation',
    continuing: 'Continuing an earlier conversation',
    deleteConversation: 'Delete',
    confirmDelete: 'Delete this conversation?',
    clearHistory: 'Clear all',
    confirmClear: 'Delete all saved conversations?',
    showHistory: 'Show conversations',
    hideHistory: 'Hide conversations',
    historyNote: 'Saved in this browser only.',
    presentation: 'Voice and avatar',
    presentationOff: 'Off (text replies only)',
    voiceFemale: 'Voice only, female',
    voiceMale: 'Voice only, male',
    avatarFemalePremium: 'Voice and avatar, female (premium)',
    avatarMale: 'Voice and avatar, male',
    loadingAvatar: 'Loading avatar…',
    avatarUnavailable: 'The avatar cannot be shown in this browser.',
    madeBy: 'by',
    switchingVoice: 'Switching voice…',
    answering: 'Answering',
    textOnly: 'Replies as text only',
    voiceOnly: 'Voice only',
    errStepsHeading: 'How to fix it',
    errDetail: 'Technical detail',
    errDismiss: 'Dismiss',
    errCopy: 'Copy',
    errCopied: 'Copied',
    errModelSettings: 'Model connection settings',
    errReconnecting: 'Connection to LiveKit interrupted. Reconnecting…',
    errProviderApi: 'API',
    errLlmMessage: '{provider} model “{model}” at {endpoint}.',
    errHttpStatus: '(HTTP {status})',
    errRecoverable: 'The agent retries automatically, so this may be temporary.',
    errLlmUnreachable: 'The language model is unreachable',
    errLlmTimeout: 'The language model did not answer in time',
    errLlmAuth: 'The language model rejected the credentials',
    errLlmEntraToken: 'Could not sign in with Microsoft Entra ID',
    errLlmModelNotFound: 'The model was not found',
    errLlmRateLimited: 'Rate limit or quota reached',
    errLlmBadRequest: 'The language model rejected the request',
    errLlmServerError: 'The language model server returned an error',
    errLlmEmptyResponse: 'The language model returned an empty reply',
    errLlmUnknown: 'The language model failed',
    errTokenTitle: 'Could not get an access token',
    errTokenMessage: 'The app server could not create a LiveKit token: {reason}',
    errLivekitAuthTitle: 'LiveKit rejected the credentials',
    errLivekitAuthMessage: 'The LiveKit server at {url} did not accept the access token.',
    errLivekitUnreachableTitle: 'Cannot reach LiveKit',
    errLivekitUnreachableMessage: 'The browser could not connect to the LiveKit server at {url}.',
    errConnectTitle: 'Could not start the conversation',
    errConnectMessage: 'Connecting to the conversation failed.',
    errConnectionLostTitle: 'Connection to LiveKit lost',
    errConnectionLostMessage: 'The conversation ended unexpectedly (reason: {reason}).',
    errAgentAbsentTitle: 'The agent did not join',
    errAgentAbsentMessage: 'No agent joined the conversation. The agent is probably not running, or it cannot reach LiveKit.',
    errAgentInitTitle: 'The agent did not finish starting',
    errAgentInitMessage: 'The agent joined but did not become ready. It may have failed while loading the wiki or the model configuration.',
    errAgentLeftTitle: 'The agent left the conversation',
    errAgentLeftMessage: 'The agent stopped, usually because the language model failed repeatedly or the agent crashed.',
    stepAgentLogs: 'Check the agent logs for details: run this command with Docker, or look at the terminal running the agent.',
    stepFrontendLogs: 'Check the app server logs: run this command with Docker, or look at the terminal running the frontend.',
    stepRestartAgent: 'After changing the configuration, restart the agent and start a new conversation.',
    stepRestartAll: 'Restart the agent and the frontend after changing them, then start again.',
    stepStartAgain: 'Start a new conversation.',
    stepOllamaStart: 'Start Ollama on the host (or open the Ollama app).',
    stepOllamaPull: 'Download the model:',
    stepOllamaModelName: 'Check that LLM_MODEL (“{model}”) matches a name in ollama list.',
    stepOllamaBaseUrl: 'Check LLM_BASE_URL (now {endpoint}); it is usually http://localhost:11434/v1.',
    stepOllamaDocker: 'If the agent runs in Docker, use host.docker.internal instead of localhost (LLM_BASE_URL_DOCKER=http://host.docker.internal:11434/v1).',
    stepOllamaApiKey: 'Ollama needs no real key: set LLM_API_KEY=ollama, or check the proxy in front of Ollama.',
    stepOllamaWarm: 'The first request loads the model into memory, which can take a while. Try again in a moment.',
    stepOllamaLogs: 'Check the Ollama logs for a crash or an out-of-memory error.',
    stepSmallerModel: 'Try a smaller model if the machine is short on memory.',
    stepApiBaseUrl: 'Check LLM_BASE_URL (now {endpoint}); it must include the /v1 path.',
    stepApiKey: 'Check LLM_API_KEY in the agent environment.',
    stepApiModel: 'Check LLM_MODEL (“{model}”); for a gateway this is the deployment name.',
    stepEntraLogin: 'For ENTRA_AUTH_MODE=cli, sign in to the right tenant with Azure CLI:',
    stepEntraScope: 'With Entra ID, check ENTRA_SCOPE, ENTRA_AUTH_MODE and the AZURE_* credentials. A 401 usually means a wrong tenant or scope; a 403 means a missing gateway role.',
    stepNetwork: 'Check DNS, VPN and proxy access from the agent to {endpoint}.',
    stepTls: 'For a private corporate CA, set NODE_EXTRA_CA_CERTS to the path of the PEM certificate.',
    stepTimeout: 'Increase LLM_TIMEOUT_S for slow models.',
    stepRateLimited: 'Wait a moment and try again, or check the quota and plan of the API account.',
    stepServerError: 'Check the status of the LLM service and try again later.',
    stepTemperature: 'If the model does not support temperature, set:',
    stepReasoning: 'Leave LLM_REASONING_EFFORT unset if the model does not support it.',
    stepCapabilities: 'Use a model that supports streaming and tool calling.',
    stepLivekitStart: 'Start LiveKit for local development:',
    stepLivekitDocker: 'Or, with Docker Compose:',
    stepLivekitPorts: 'Make sure ports 7880 and 7881 (TCP) and 7882 (UDP) are open and not used by another program.',
    stepLivekitUrl: 'Check LIVEKIT_URL (now {url}); the browser must be able to reach it.',
    stepLivekitKeys: 'LIVEKIT_API_KEY and LIVEKIT_API_SECRET must be the same for LiveKit, the agent and the frontend (devkey / secret for livekit-server --dev).',
    stepLivekitRunning: 'Check that LiveKit is still running:',
    stepNetworkBrowser: 'Check the network connection of this device (Wi-Fi, VPN, sleep mode).',
    stepWikiSources: 'Check WIKI_SOURCES: it must be a JSON array of { id, name, path } objects.',
    stepAgentStart: 'Start the agent:',
    stepAgentDocker: 'Or, with Docker Compose:',
    stepAgentConfig: 'Check that the agent uses the same LIVEKIT_URL, LIVEKIT_API_KEY, LIVEKIT_API_SECRET and AGENT_NAME as the frontend.',
  },
  nl: {
    title: 'Praat met de wiki',
    subtitle: 'Stel hardop vragen over de code. Code en details verschijnen op het scherm.',
    start: 'Gesprek starten',
    connecting: 'Verbinden…',
    waiting: 'Wachten op de agent…',
    listening: 'Luistert',
    thinking: 'Denkt na',
    speaking: 'Spreekt',
    hearing: 'Luisteren…',
    transcribing: 'Spraak verwerken…',
    preparing: 'Antwoord voorbereiden…',
    end: 'Stoppen',
    typePlaceholder: 'Of typ een vraag…',
    send: 'Versturen',
    stop: 'Stop',
    stopSpeaking: 'Stoppen met praten',
    transcript: 'Transcript',
    onScreen: 'Op het scherm',
    sources: 'Bronnen',
    noSources: 'Gebruikte pagina’s verschijnen hier.',
    close: 'Sluiten',
    language: 'Taal',
    pushToTalk: 'Drukken om te praten',
    holdToTalk: 'Ingedrukt houden om te praten (of houd spatie ingedrukt)',
    talking: 'Loslaten om te versturen',
    noSpeechModel: 'Kies een spraakmodel in de spraakinstellingen om te praten',
    loadingSpeechModel: 'Spraakmodel laden…',
    speechModelFailed: 'Het spraakmodel kon niet worden geladen. Kijk in de spraakinstellingen.',
    micUnavailable: 'De microfoon is niet beschikbaar.',
    settings: 'Instellingen',
    modelConnection: 'Modelverbinding',
    configuredProvider: 'Ingestelde provider',
    configuredAuth: 'Authenticatie',
    apiKeyAuth: 'API-sleutel / lokale placeholder',
    entraSetup: 'Microsoft Entra ID / Enterprise-gateway instellen',
    entraIntro: 'Gebruik de OpenAI-v1-API van de gateway. Stel het model in op een deploymentnaam, niet een algemene modelnaam. Regel de vereiste gateway- en modelrechten en een geautoriseerd account of een identity bij je organisatie. Vervang het voorbeeldendpoint en de resourcescope door de waarden van je gatewaybeheerder. LLM_API_KEY is niet nodig: Azure Identity bewaart en vernieuwt toegangstokens automatisch.',
    entraCli: 'Installeer voor native lokale ontwikkeling Azure CLI en meld je aan bij de tenant met gatewaytoegang voordat je de agent start. Het standaard Docker-image bevat geen Azure CLI of je hostaanmelding; gebruik in Compose de service-principalmodus.',
    entraServicePrincipal: 'Gebruik voor Docker of deployments buiten Azure een geautoriseerde service principal. Bewaar het geheim alleen in de serveromgeving van de agent. Gebruik het applicatie-ID (client-ID), niet het object-ID; gebruik het geheim nooit als LLM_API_KEY. Auto kiest service-principalauthenticatie als een AZURE_*-credentialveld is ingesteld (alle drie zijn dan vereist), anders Azure CLI.',
    entraManagedIdentity: 'Stel op een Azure-host met managed identity ENTRA_AUTH_MODE=managed-identity in. Zet voor een user-assigned identity ook AZURE_CLIENT_ID op het client-ID en ken gatewayrollen toe. Zonder dit ID wordt de system-assigned identity gebruikt. Een client secret is niet nodig; deze modus gebruikt geen gefedereerde AKS-workloadidentiteit.',
    entraProduction: 'Een productievoorbeeld is https://api.example.com/openai/v1 met ENTRA_SCOPE=api://api.example.com/.default. Vervang beide door de waarden van je gateway; endpoint en scope moeten bij dezelfde omgeving horen. Laat reasoning effort leeg; gebruik LLM_TEMPERATURE=omit als de deployment temperature niet ondersteunt. Een 401 kan op een verkeerde tenant of scope wijzen; een 403 betekent meestal ontbrekende rechten.',
    entraCa: 'Exporteer voor een interne CA NODE_EXTRA_CA_CERTS met het pad naar een PEM-certificaat voordat Node start. Mount in Docker het certificaat alleen-lezen en gebruik het pad in de container. Schakel TLS-controle niet uit. Volledige voorbeelden staan in de README van de repository.',
    configuredModel: 'Ingesteld model',
    legacyProvider: 'OpenAI-compatibel endpoint (bestaande configuratie)',
    modelNotSet: 'Niet ingesteld',
    modelConfigNote: 'Serverconfiguratie, geen controle van de verbinding. Wijzigingen gelden voor nieuwe gesprekken na het herstarten van de diensten.',
    apiSetup: 'Een externe API instellen',
    apiSetupIntro: 'Maak een API-sleutel bij OpenAI of een OpenAI-compatibele provider. Kies een chat-completionmodel met streaming en toolaanroepen en zet deze waarden in de serveromgeving. Vervang het model en de sleutel; gebruik de API-basis-URL van je provider.',
    apiSetupKey: 'Bewaar de echte sleutel alleen in de serveromgeving of een omgevingsbestand dat niet wordt gecommit. Gebruik nooit browseropslag of NEXT_PUBLIC_*-variabelen. Native Anthropic- en Gemini-API’s vereisen een compatibele gateway en worden niet rechtstreeks ondersteund.',
    apiDockerOverride: 'Verwijder voor Docker een oude LLM_BASE_URL_DOCKER of wijzig deze naar dezelfde API-URL: deze heeft voorrang op LLM_BASE_URL. Ollama-containers en -images zijn niet nodig.',
    modelPrivacy: 'Externe providers ontvangen je vragen, wiki-fragmenten, toolresultaten en gesprekscontext, inclusief herstelde geschiedenis. API-gebruik kan geld kosten. Spraakherkenning en stemmen blijven in deze browser. Beperk openbare toegang om ongewenste API-kosten te voorkomen.',
    ollamaSetup: 'Ollama instellen',
    ollamaNative: 'Installeer Ollama via ollama.com en start het op de host (zo nodig met ollama serve). Download een model met toolondersteuning en gebruik deze serverinstellingen. Native Ollama is sneller op macOS omdat Docker geen Metal kan gebruiken.',
    ollamaDocker: 'Gebruik voor Ollama in Docker de instellingen hierboven plus deze endpoint-override. Het optionele ollama-profiel start Ollama en downloadt LLM_MODEL. Stel eerst een Ollama-modelnaam in, niet de naam van een extern API-model.',
    ollamaHost: 'Gebruik met een Docker-agent en native Ollama LLM_BASE_URL_DOCKER=http://host.docker.internal:11434/v1. Gebruik voor een native agent localhost; gebruik voor beide in Compose de servicenaam ollama. Localhost in Docker is niet je hostmachine.',
    ollamaProd: 'Voeg voor gepubliceerde productie-images -f docker-compose.prod.yml toe aan de Docker-opdrachten en laat --build weg. Ollama-images worden alleen gedownload en gestart als het ollama-profiel is ingeschakeld.',
    modelApply: 'Wijzigingen toepassen of terug naar Ollama',
    modelEnv: 'Native diensten lezen .env.local in de repository vóór .env. Compose leest standaard .env; voeg --env-file .env.local toe aan elke Compose-opdracht als je dat bestand gebruikt.',
    modelRestart: 'Herstart na wijzigingen de native agent en frontend, of maak beide containers opnieuw aan met de opdracht hieronder. Alleen een Docker-herstart laadt geen nieuwe omgevingswaarden. Beëindig een bestaand gesprek en start een nieuw gesprek.',
    modelFallback: 'Terugvallen gebeurt handmatig, nooit automatisch: stel LLM_PROVIDER=ollama en LLM_AUTH=api-key in, herstel een Ollama-model, endpoint en LLM_API_KEY=ollama en maak de diensten opnieuw aan. Start native Ollama of schakel het Docker-profiel in. Bij een API-fout gaat je gesprek niet stilzwijgend naar een andere provider.',
    modelTroubleshooting: 'Bekijk de agentlogs: bij authenticatiefouten klopt meestal de sleutel, Entra-aanmelding of tokenscope niet; bij model-not-found klopt het model/deployment-ID of de API-basis-URL niet. Controleer bij verbindingsfouten de hostnaam en dienst. Verhoog LLM_TIMEOUT_S bij trage modellen; gebruik LLM_TEMPERATURE=omit of laat LLM_REASONING_EFFORT leeg als deze niet worden ondersteund. Modellen moeten streaming en toolaanroepen ondersteunen.',
    speechSettings: 'Spraakinstellingen',
    settingsTitle: 'Spraakherkenning',
    settingsIntro:
      'Spraakherkenning en stemmen draaien hier in de browser. Download ze één keer; de browser bewaart ze voor de volgende keer.',
    backToApp: 'Terug naar het gesprek',
    thisBrowser: 'Deze browser',
    webgpuYes: 'WebGPU beschikbaar: modellen draaien op de grafische kaart.',
    webgpuNoF16: 'WebGPU beschikbaar, zonder 16-bit float-ondersteuning: het grootste model is niet beschikbaar.',
    webgpuNo: 'Geen WebGPU: modellen draaien op de processor, wat trager is. Chrome en Edge ondersteunen WebGPU.',
    storageUsed: 'Gebruikte opslag',
    recommended: 'Aanbevolen',
    inUse: 'In gebruik',
    use: 'Gebruiken',
    download: 'Downloaden',
    resumeDownload: 'Download hervatten',
    downloading: 'Downloaden…',
    cancel: 'Annuleren',
    remove: 'Verwijderen',
    confirmRemove: 'Dit model uit de browser verwijderen?',
    downloaded: 'Gedownload',
    partlyDownloaded: 'Deels gedownload',
    notDownloaded: 'Niet gedownload',
    needsWebgpuF16: 'Vereist WebGPU met 16-bit float-ondersteuning',
    downloadFailed: 'Downloaden mislukt',
    tryIt: 'Uitproberen',
    tryItHint: 'Houd de knop (of spatie) ingedrukt en zeg iets.',
    tryItNoModel: 'Download eerst een model en selecteer het.',
    nothingRecognized: 'Niets herkend.',
    transcribedIn: 'Omgezet in',
    voices: 'Stemmen',
    voicesIntro:
      'Antwoorden worden uitgesproken door een stem die in deze browser draait. Download de stemmen voor de talen die je gebruikt.',
    female: 'Vrouw',
    male: 'Man',
    wordTimings: 'Woordtiming (lipsync van de avatar)',
    confirmRemoveVoice: 'Deze stem uit de browser verwijderen?',
    tryVoice: 'Een stem uitproberen',
    tryVoiceNone: 'Download eerst een stem.',
    speak: 'Uitspreken',
    preparingSpeech: 'Spraak voorbereiden…',
    voiceFailed: 'De stem werkt niet:',
    firstAudioAfter: 'Eerste geluid na',
    speechLength: 'spraak',
    synthesizedIn: 'gemaakt in',
    instantTranscript: 'Dialoog zonder vertraging tonen',
    instantTranscriptNote: 'Toon antwoorden zodra ze binnenkomen, in plaats van samen met de stem.',
    voiceMissing: 'De stem voor deze taal is niet gedownload; antwoorden zijn alleen tekst.',
    voiceFailedShort: 'De stem kon niet worden afgespeeld; antwoorden zijn alleen tekst.',
    empty: 'Zeg hallo, of vraag bijvoorbeeld "Hoe worden Stripe-webhooks opnieuw geprobeerd?"',
    history: 'Gesprekken',
    noHistory: 'Eerdere gesprekken verschijnen hier.',
    today: 'Vandaag',
    yesterday: 'Gisteren',
    previous7Days: 'Afgelopen 7 dagen',
    untitled: 'Gesprek',
    continueConversation: 'Gesprek voortzetten',
    continuing: 'Een eerder gesprek wordt voortgezet',
    deleteConversation: 'Verwijderen',
    confirmDelete: 'Dit gesprek verwijderen?',
    clearHistory: 'Alles wissen',
    confirmClear: 'Alle bewaarde gesprekken verwijderen?',
    showHistory: 'Gesprekken tonen',
    hideHistory: 'Gesprekken verbergen',
    historyNote: 'Alleen in deze browser bewaard.',
    presentation: 'Stem en avatar',
    presentationOff: 'Uit (alleen tekstantwoorden)',
    voiceFemale: 'Alleen stem, vrouw',
    voiceMale: 'Alleen stem, man',
    avatarFemalePremium: 'Stem en avatar, vrouw (premium)',
    avatarMale: 'Stem en avatar, man',
    loadingAvatar: 'Avatar laden…',
    avatarUnavailable: 'De avatar kan in deze browser niet worden getoond.',
    madeBy: 'door',
    switchingVoice: 'Stem wisselen…',
    answering: 'Antwoordt',
    textOnly: 'Antwoorden alleen als tekst',
    voiceOnly: 'Alleen stem',
    errStepsHeading: 'Zo los je het op',
    errDetail: 'Technische details',
    errDismiss: 'Sluiten',
    errCopy: 'Kopiëren',
    errCopied: 'Gekopieerd',
    errModelSettings: 'Instellingen voor de modelverbinding',
    errReconnecting: 'Verbinding met LiveKit onderbroken. Opnieuw verbinden…',
    errProviderApi: 'API',
    errLlmMessage: '{provider}-model “{model}” op {endpoint}.',
    errHttpStatus: '(HTTP {status})',
    errRecoverable: 'De agent probeert het automatisch opnieuw, dus dit kan tijdelijk zijn.',
    errLlmUnreachable: 'Het taalmodel is niet bereikbaar',
    errLlmTimeout: 'Het taalmodel antwoordde niet op tijd',
    errLlmAuth: 'Het taalmodel weigerde de inloggegevens',
    errLlmEntraToken: 'Aanmelden met Microsoft Entra ID is mislukt',
    errLlmModelNotFound: 'Het model is niet gevonden',
    errLlmRateLimited: 'Limiet of quotum bereikt',
    errLlmBadRequest: 'Het taalmodel weigerde het verzoek',
    errLlmServerError: 'De server van het taalmodel gaf een fout',
    errLlmEmptyResponse: 'Het taalmodel gaf een leeg antwoord',
    errLlmUnknown: 'Het taalmodel gaf een fout',
    errTokenTitle: 'Kon geen toegangstoken krijgen',
    errTokenMessage: 'De appserver kon geen LiveKit-token maken: {reason}',
    errLivekitAuthTitle: 'LiveKit weigerde de inloggegevens',
    errLivekitAuthMessage: 'De LiveKit-server op {url} accepteerde het toegangstoken niet.',
    errLivekitUnreachableTitle: 'LiveKit is niet bereikbaar',
    errLivekitUnreachableMessage: 'De browser kon geen verbinding maken met de LiveKit-server op {url}.',
    errConnectTitle: 'Kon het gesprek niet starten',
    errConnectMessage: 'Verbinden met het gesprek is mislukt.',
    errConnectionLostTitle: 'Verbinding met LiveKit verbroken',
    errConnectionLostMessage: 'Het gesprek is onverwacht beëindigd (reden: {reason}).',
    errAgentAbsentTitle: 'De agent kwam niet in het gesprek',
    errAgentAbsentMessage: 'Er kwam geen agent in het gesprek. Waarschijnlijk draait de agent niet, of kan hij LiveKit niet bereiken.',
    errAgentInitTitle: 'De agent is niet klaar met opstarten',
    errAgentInitMessage: 'De agent kwam binnen maar werd niet gereed. Mogelijk ging het laden van de wiki of de modelconfiguratie mis.',
    errAgentLeftTitle: 'De agent heeft het gesprek verlaten',
    errAgentLeftMessage: 'De agent is gestopt, meestal omdat het taalmodel herhaaldelijk faalde of de agent crashte.',
    stepAgentLogs: 'Bekijk de agentlogs voor details: voer met Docker dit commando uit, of kijk in de terminal waarin de agent draait.',
    stepFrontendLogs: 'Bekijk de logs van de appserver: voer met Docker dit commando uit, of kijk in de terminal waarin de frontend draait.',
    stepRestartAgent: 'Herstart na het aanpassen van de configuratie de agent en start een nieuw gesprek.',
    stepRestartAll: 'Herstart de agent en de frontend na het aanpassen, en start opnieuw.',
    stepStartAgain: 'Start een nieuw gesprek.',
    stepOllamaStart: 'Start Ollama op de host (of open de Ollama-app).',
    stepOllamaPull: 'Download het model:',
    stepOllamaModelName: 'Controleer of LLM_MODEL (“{model}”) overeenkomt met een naam in ollama list.',
    stepOllamaBaseUrl: 'Controleer LLM_BASE_URL (nu {endpoint}); meestal is dat http://localhost:11434/v1.',
    stepOllamaDocker: 'Draait de agent in Docker, gebruik dan host.docker.internal in plaats van localhost (LLM_BASE_URL_DOCKER=http://host.docker.internal:11434/v1).',
    stepOllamaApiKey: 'Ollama heeft geen echte sleutel nodig: zet LLM_API_KEY=ollama, of controleer de proxy voor Ollama.',
    stepOllamaWarm: 'Bij het eerste verzoek wordt het model in het geheugen geladen; dat kan even duren. Probeer het zo opnieuw.',
    stepOllamaLogs: 'Bekijk de Ollama-logs op een crash of een tekort aan geheugen.',
    stepSmallerModel: 'Probeer een kleiner model als de machine weinig geheugen heeft.',
    stepApiBaseUrl: 'Controleer LLM_BASE_URL (nu {endpoint}); het pad /v1 moet erin staan.',
    stepApiKey: 'Controleer LLM_API_KEY in de omgeving van de agent.',
    stepApiModel: 'Controleer LLM_MODEL (“{model}”); bij een gateway is dit de deploymentnaam.',
    stepEntraLogin: 'Meld je bij ENTRA_AUTH_MODE=cli met Azure CLI aan bij de juiste tenant:',
    stepEntraScope: 'Controleer bij Entra ID ENTRA_SCOPE, ENTRA_AUTH_MODE en de AZURE_*-gegevens. Een 401 betekent meestal een verkeerde tenant of scope; een 403 een ontbrekende gatewayrol.',
    stepNetwork: 'Controleer DNS-, VPN- en proxytoegang van de agent naar {endpoint}.',
    stepTls: 'Zet bij een eigen bedrijfs-CA NODE_EXTRA_CA_CERTS op het pad van het PEM-certificaat.',
    stepTimeout: 'Verhoog LLM_TIMEOUT_S bij trage modellen.',
    stepRateLimited: 'Wacht even en probeer het opnieuw, of controleer het quotum en abonnement van het API-account.',
    stepServerError: 'Controleer de status van de LLM-dienst en probeer het later opnieuw.',
    stepTemperature: 'Ondersteunt het model geen temperatuur, zet dan:',
    stepReasoning: 'Laat LLM_REASONING_EFFORT leeg als het model dit niet ondersteunt.',
    stepCapabilities: 'Gebruik een model dat streaming en toolaanroepen ondersteunt.',
    stepLivekitStart: 'Start LiveKit voor lokale ontwikkeling:',
    stepLivekitDocker: 'Of met Docker Compose:',
    stepLivekitPorts: 'Zorg dat poorten 7880 en 7881 (TCP) en 7882 (UDP) open zijn en niet door een ander programma worden gebruikt.',
    stepLivekitUrl: 'Controleer LIVEKIT_URL (nu {url}); de browser moet die kunnen bereiken.',
    stepLivekitKeys: 'LIVEKIT_API_KEY en LIVEKIT_API_SECRET moeten gelijk zijn voor LiveKit, de agent en de frontend (devkey / secret bij livekit-server --dev).',
    stepLivekitRunning: 'Controleer of LiveKit nog draait:',
    stepNetworkBrowser: 'Controleer de netwerkverbinding van dit apparaat (wifi, VPN, slaapstand).',
    stepWikiSources: 'Controleer WIKI_SOURCES: dat moet een JSON-array van { id, name, path }-objecten zijn.',
    stepAgentStart: 'Start de agent:',
    stepAgentDocker: 'Of met Docker Compose:',
    stepAgentConfig: 'Controleer of de agent dezelfde LIVEKIT_URL, LIVEKIT_API_KEY, LIVEKIT_API_SECRET en AGENT_NAME gebruikt als de frontend.',
  },
} satisfies Record<Language, Record<string, string>>;

export type Strings = (typeof STRINGS)['en'];

// Fails to compile when a key exists in one language but not the other.
type MissingKeys = Exclude<keyof Strings, keyof (typeof STRINGS)['nl']> | Exclude<keyof (typeof STRINGS)['nl'], keyof Strings>;
const sameKeys: [MissingKeys] extends [never] ? true : MissingKeys = true;
void sameKeys;
